name: Rust

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      working-directory: src/libcustomvmcpu
      run: cargo build --verbose
    - name: Run tests
      working-directory: src/libcustomvmcpu
      run: cargo test --verbose
